-- ─────────────────────────────────────────────────────────────────────────────
-- Event-leads import — generert automatisk
-- Kjør i: Supabase Dashboard → SQL Editor
-- ─────────────────────────────────────────────────────────────────────────────

INSERT INTO leads
  (name, first_name, last_name, email, phone, source, status, value,
   sentiment, urgency, intent, last_activity, summary, requirements)
VALUES
  ('Kai Evjen', 'Kai', 'Evjen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Veldig bra Leads: Kai Evjen og Roger Tangen', '{}'::jsonb),
  ('Roger Tangen', 'Roger', 'Tangen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Veldig bra Leads: Kai Evjen og Roger Tangen', '{}'::jsonb),
  ('Maria Hanson', 'Maria', 'Hanson', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, '', '{}'::jsonb),
  ('Inger Lise Pettersen', 'Inger Lise', 'Pettersen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, '', '{}'::jsonb),
  ('Jan Pedersen', 'Jan', 'Pedersen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, '', '{}'::jsonb),
  ('Keyvan Keshtkar', 'Keyvan', 'Keshtkar', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, '', '{}'::jsonb),
  ('Aileen Strøm', 'Aileen', 'Strøm', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, '', '{}'::jsonb),
  ('Gaute Marcussen', 'Gaute', 'Marcussen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Gode leads på: Gaute Marcussen og Helge Tryti.', '{}'::jsonb),
  ('Helge Tryti', 'Helge', 'Tryti', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Gode leads på: Gaute Marcussen og Helge Tryti.', '{}'::jsonb),
  ('Paula Castillo Mendoza', 'Paula Castillo', 'Mendoza', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, '', '{}'::jsonb),
  ('Ali Al-Anini', 'Ali', 'Al-Anini', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Ali Al-Anini: Ett mulig godt lead, en plastisk kirurg fra Iran? tenker på investering. Vil prate lån, finans, nedbetaling etc. Vil ta med en kamerat også. De er opptatt nå men om noen uker er de klare til møte. Sønnen måtte i bursdag og måtte derfor kansellere', '{}'::jsonb),
  ('Arne Sæther', 'Arne', 'Sæther', '', '', 'Event Import', 'NEW', 200000, 50, 50, 50, NOW()::text, 'Bra lead på Arne Sæther | Bra lead på Arne Sæther, de kommer til å kjøpe med tiden.  budsjett 200 000 euro, nybygg ferdig 2024. de vil spare penger og kjøpe det som er gunstig.MS syk kone, trenger varme og sol | Budsjett: 200 000 euro, nybygg ferdig 2024', '{"budget_text":"200 000 euro, nybygg ferdig 2024"}'::jsonb),
  ('Tone Stene', 'Tone', 'Stene', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Tone Stene & Stig Thoresen (De er med meg til Spania denne uken - visningstur)', '{}'::jsonb),
  ('Stig Thoresen', 'Stig', 'Thoresen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Tone Stene & Stig Thoresen (De er med meg til Spania denne uken - visningstur)', '{}'::jsonb),
  ('Jan Ove Meli', 'Jan Ove', 'Meli', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Jan Ove Meli - Gode Leads.', '{}'::jsonb),
  ('Ståle Rylandsholm', 'Ståle', 'Rylandsholm', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Ståle Rylandsholm - Gode Leads. - 300 - 400 k nybygg, Torrevieja til Allicante | Lokasjon: Torrevieja', '{"location":"Torrevieja"}'::jsonb),
  ('Hege Therese Fjell', 'Hege Therese', 'Fjell', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Hege Therese Fjell - Gode Leads. Ønsker CB NORD | Lokasjon: CB Nord', '{"location":"CB Nord"}'::jsonb),
  ('Vidar Torbjørnsen', 'Vidar', 'Torbjørnsen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Vidar Torbjørnsen - ønsker Villamartin etc.. ikke nord for flyplassen. Sendt leads til Janne | Lokasjon: Villamartin', '{"location":"Villamartin"}'::jsonb),
  ('Stig Helge Røsland', 'Stig Helge', 'Røsland', '', '', 'Event Import', 'NEW', 500000, 50, 50, 50, NOW()::text, 'Stig Helge Røsland - Gode Leads. 3-5 MNOK. Sendt Leads til Janne | Budsjett: 5 MNOK', '{"budget_text":"5 MNOK"}'::jsonb),
  ('Jan Gisle Askeland', 'Jan Gisle', 'Askeland', '', '', 'Event Import', 'NEW', 500000, 50, 50, 50, NOW()::text, 'Jan Gisle Askeland - 3-5MNOK | Budsjett: 5MNOK', '{"budget_text":"5MNOK"}'::jsonb),
  ('Magne Haugum', 'Magne', 'Haugum', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Magne Haugum - Gode Leads (kjøper i mai/juni)', '{}'::jsonb),
  ('Arvid Rønning', 'Arvid', 'Rønning', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Arvid Rønning - Gode Leads. Vurderer visningstur i mars/april. CB Sør | Lokasjon: CB Sør', '{"location":"CB Sør"}'::jsonb),
  ('Eirik Nørgaard', 'Eirik', 'Nørgaard', '', '', 'Event Import', 'NEW', 300000, 50, 50, 50, NOW()::text, 'Eirik Nørgaard: Vil ta kontakt på nyåret (ca nov 2024) 2-3 soverom, maks 3MNOK - gjerne i Orihuela Costa. | Budsjett: 3MNOK | Lokasjon: Orihuela Costa', '{"budget_text":"3MNOK","location":"Orihuela Costa"}'::jsonb),
  ('Nina Schjønsby', 'Nina', 'Schjønsby', '', '', 'Event Import', 'NEW', 400000, 50, 50, 50, NOW()::text, 'Nina Schjønsby: Ca 400K EURO +omk - vil kjøpe i Estepona - men ikke per nå. Vi tar kontakt etter sommeren (høsten 2024) | Budsjett: 400K EUR | Lokasjon: Estepona', '{"budget_text":"400K EUR","location":"Estepona"}'::jsonb),
  ('Jon Hauger', 'Jon', 'Hauger', '', '', 'Event Import', 'NEW', 350000, 50, 50, 50, NOW()::text, 'Jon Hauger: Budsjet maks 3,5 MNOK. Sendt prospekter - vi avtaler neste steg... | Budsjett: 3,5 MNOK', '{"budget_text":"3,5 MNOK"}'::jsonb),
  ('Rune Torgersen', 'Rune', 'Torgersen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Rune Torgersen', '{}'::jsonb),
  ('Rolf Tvenge', 'Rolf', 'Tvenge', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Rolf Tvenge', '{}'::jsonb),
  ('Eivind Helgesen', 'Eivind', 'Helgesen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Eivind Helgesen', '{}'::jsonb),
  ('Kristin Strøm', 'Kristin', 'Strøm', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Kristin Strøm', '{}'::jsonb),
  ('Bård Berntsen', 'Bård', 'Berntsen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Bård Berntsen', '{}'::jsonb),
  ('Vidar Andersen', 'Vidar', 'Andersen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Vidar Andersen', '{}'::jsonb),
  ('Jan Robert Rød', 'Jan Robert', 'Rød', '', '', 'Event Import', 'NEW', 400000, 50, 50, 50, NOW()::text, 'Jan Robert Rød: veldig god leads. Budsjett 2 | Budsjett: 2,5-4 mill nok', '{"budget_text":"2,5-4 mill nok"}'::jsonb),
  ('Tore Morkmo', 'Tore', 'Morkmo', '', '', 'Event Import', 'NEW', 500000, 50, 50, 50, NOW()::text, 'Tore Morkmo: Har god tid. Skal kjøpe om 3 år. | Budsjett: 5 mill | Lokasjon: Costa del Sol', '{"budget_text":"5 mill","location":"Costa del Sol"}'::jsonb),
  ('Bjørn Ole Rislå', 'Bjørn Ole', 'Rislå', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Bjørn Ole Rislå', '{}'::jsonb),
  ('Lars Grøseth', 'Lars', 'Grøseth', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Lars Grøseth', '{}'::jsonb),
  ('Jørn Nilsen', 'Jørn', 'Nilsen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Jørn Nilsen', '{}'::jsonb),
  ('Egil Solberg', 'Egil', 'Solberg', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Egil Solberg', '{}'::jsonb),
  ('Rolf Erling Lona', 'Rolf Erling', 'Lona', '', '', 'Event Import', 'NEW', 500000, 50, 50, 50, NOW()::text, 'Rolf Erling Lona | Rolf Erling Lona - Sendt han i Amo i dag på Del Sol - Investerer, i prosess. Vil ha Del Sol. Følges opp i Amo. | Rolf Erling Lona, Budsjett 500k. CDS Estepona ++  Investerer i egen helse, og varme | Budsjett: 500k | Lokasjon: CDS', '{"budget_text":"500k","location":"CDS"}'::jsonb),
  ('Terje Opland', 'Terje', 'Opland', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Terje Opland | Terje Opland, - Investerer, 350-400k, skal flytte ned om 3 år. CB Nord | Lokasjon: CB Nord', '{"location":"CB Nord"}'::jsonb),
  ('Frank Løvåsen', 'Frank', 'Løvåsen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Frank Løvåsen', '{}'::jsonb),
  ('Nina Beate Larsen', 'Nina Beate', 'Larsen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Nina Beate Larsen', '{}'::jsonb),
  ('Ole Kristian Solbakken', 'Ole Kristian', 'Solbakken', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Ole Kristian Solbakken', '{}'::jsonb),
  ('Arild Hjelmseth', 'Arild', 'Hjelmseth', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Arild Hjelmseth', '{}'::jsonb),
  ('Ove Andre Solbrekke', 'Ove Andre', 'Solbrekke', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Ove Andre Solbrekke', '{}'::jsonb),
  ('Geir Øivind Sætre', 'Geir Øivind', 'Sætre', '', '', 'Event Import', 'NEW', 500000, 50, 50, 50, NOW()::text, 'Geir Øivind Sætre - budsjett 5MNOK . Vil flytte ned fast . CB SØR - Villamartin - La Zenia - Torrevieja . Sender i Amo til Janne | Budsjett: 5MNOK | Lokasjon: CB Sør', '{"budget_text":"5MNOK","location":"CB Sør"}'::jsonb),
  ('Hanne Eide', 'Hanne', 'Eide', '', '', 'Event Import', 'NEW', 500000, 50, 50, 50, NOW()::text, 'Hanne Eide - Kjøpe for å reise fra snøen, Budsjett 5 MNOK. Vurderer CB Nord .  Sender i Amo . | Budsjett: 5 MNOK | Lokasjon: CB Nord', '{"budget_text":"5 MNOK","location":"CB Nord"}'::jsonb),
  ('Morten Granhaug', 'Morten', 'Granhaug', '', '', 'Event Import', 'NEW', 200000, 50, 50, 50, NOW()::text, 'Morten Granhaug - Følges opp  Har bolig fra før i spania men vil kjøpe en til, og ha næreheten av den andre. Torrevieja , punta Prima, playa flamenca .  Budsjett 2 MNOK Sender i Amo . | Budsjett: 2 MNOK Sender i Amo | Lokasjon: Torrevieja', '{"budget_text":"2 MNOK Sender i Amo","location":"Torrevieja"}'::jsonb),
  ('Ole I Stange', 'Ole I', 'Stange', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Ole I Stange, Investering sammen med barn - 450k-550k + omk .  Vil bli kontaktet når han er hjemme fra reise i april/mai', '{}'::jsonb),
  ('Nina Larsen', 'Nina', 'Larsen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Nina Larsen, var kun med av nyskjerrighet', '{}'::jsonb),
  ('Tone Gammelrud', 'Tone', 'Gammelrud', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Tone Gammelrud, Skal leie bolig først ett år, og evt kjøpe neste år. Har ikke finans i orden.', '{}'::jsonb),
  ('Arild Hjelmeseth', 'Arild', 'Hjelmeseth', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Arild Hjelmeseth', '{}'::jsonb),
  ('Hanne M C Ovesen', 'Hanne M C', 'Ovesen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Hanne M C Ovesen', '{}'::jsonb),
  ('Siv Aune', 'Siv', 'Aune', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Siv Aune', '{}'::jsonb),
  ('Tor Erik Leksås', 'Tor Erik', 'Leksås', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Tor Erik Leksås', '{}'::jsonb),
  ('Gjertrud Marie Valen', 'Gjertrud Marie', 'Valen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Gjertrud Marie Valen', '{}'::jsonb),
  ('Jan Petter Aarskog', 'Jan Petter', 'Aarskog', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Jan Petter Aarskog', '{}'::jsonb),
  ('Frank Eikeland', 'Frank', 'Eikeland', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Frank Eikeland', '{}'::jsonb),
  ('Lars Rønning', 'Lars', 'Rønning', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Lars Rønning', '{}'::jsonb),
  ('Nina Løbæk', 'Nina', 'Løbæk', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Nina Løbæk', '{}'::jsonb),
  ('Gunnar Thoresen', 'Gunnar', 'Thoresen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Gunnar Thoresen | Gunnar Thoresen , Skal kjøpe om 3 år . Følges opp', '{}'::jsonb),
  ('May Kristin Giske', 'May Kristin', 'Giske', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'May Kristin Giske', '{}'::jsonb),
  ('Bjørn Magne Halvorsen', 'Bjørn Magne', 'Halvorsen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Bjørn Magne Halvorsen', '{}'::jsonb),
  ('Frode Kvamshagen', 'Frode', 'Kvamshagen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Frode Kvamshagen', '{}'::jsonb),
  ('Rolf Petter Almklov', 'Rolf Petter', 'Almklov', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Rolf Petter Almklov', '{}'::jsonb),
  ('Stein Alstad', 'Stein', 'Alstad', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Stein Alstad', '{}'::jsonb),
  ('Anne Brit Ødegård', 'Anne Brit', 'Ødegård', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Anne Brit Ødegård', '{}'::jsonb),
  ('Marius Nåvik', 'Marius', 'Nåvik', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Marius Nåvik', '{}'::jsonb),
  ('Jan Tore Nossen', 'Jan Tore', 'Nossen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Jan Tore Nossen', '{}'::jsonb),
  ('Stig Arne Arnesen', 'Stig Arne', 'Arnesen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Stig Arne Arnesen', '{}'::jsonb),
  ('Trine Oskarsen', 'Trine', 'Oskarsen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Trine Oskarsen', '{}'::jsonb),
  ('Inghild Fari', 'Inghild', 'Fari', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Inghild Fari', '{}'::jsonb),
  ('Tone Bjerke', 'Tone', 'Bjerke', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Tone Bjerke', '{}'::jsonb),
  ('Tom Lunden', 'Tom', 'Lunden', '', '', 'Event Import', 'NEW', 300000, 50, 50, 50, NOW()::text, 'Tom Lunden | Tom Lunden, har veldig lyst og vil kjøpe i Estepona - 300 000 euro | Tom Lunden og kone, ønsker leilighet på CDS Estepona 400-500K Sendt til CDS | Budsjett: 300 000 euro | Lokasjon: Estepona', '{"budget_text":"300 000 euro","location":"Estepona"}'::jsonb),
  ('Arild Pettersen', 'Arild', 'Pettersen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Arild Pettersen', '{}'::jsonb),
  ('Siri Flesche', 'Siri', 'Flesche', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Siri Flesche', '{}'::jsonb),
  ('Jan Erik Syversen', 'Jan Erik', 'Syversen', '', '', 'Event Import', 'NEW', 500000, 50, 50, 50, NOW()::text, 'Jan Erik Syversen | Jan Erik Syversen og kona har budsjett på 5 mill - vurderer del sol ! | Budsjett: på 5 mill - vurderer del sol !', '{"budget_text":"på 5 mill - vurderer del sol !"}'::jsonb),
  ('Kjell Johansen', 'Kjell', 'Johansen', '', '', 'Event Import', 'NEW', 350000, 50, 50, 50, NOW()::text, 'Kjell Johansen | Kjell Johansen - har sett mye, ønsker Estepona/Manilva/Casares . Er sykemeldt pga noe greier. Men kjøper for 350 000 eur | Budsjett: 350 000 eur | Lokasjon: Estepona', '{"budget_text":"350 000 eur","location":"Estepona"}'::jsonb),
  ('Roar Ruste', 'Roar', 'Ruste', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Roar Ruste', '{}'::jsonb),
  ('Pia Østerløf', 'Pia', 'Østerløf', '', '', 'Event Import', 'NEW', 500000, 50, 50, 50, NOW()::text, 'Pia Østerløf | Pia Østerløf, budsjett inntil 5 MNOK. Kjøpe innen 2 år. Vurderer CB SØR. Sender til amo | Budsjett: inntil 5 MNOK | Lokasjon: CB Sør', '{"budget_text":"inntil 5 MNOK","location":"CB Sør"}'::jsonb),
  ('Espen Myrvold', 'Espen', 'Myrvold', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Espen Myrvold', '{}'::jsonb),
  ('Ewa Olofsdotter', 'Ewa', 'Olofsdotter', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Ewa Olofsdotter', '{}'::jsonb),
  ('Bård Olav Støen', 'Bård Olav', 'Støen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Bård Olav Støen', '{}'::jsonb),
  ('Steinar Halvorsen', 'Steinar', 'Halvorsen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Steinar Halvorsen', '{}'::jsonb),
  ('Pål Eie', 'Pål', 'Eie', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Pål Eie', '{}'::jsonb),
  ('Tor Erik Sandum', 'Tor Erik', 'Sandum', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Tor Erik Sandum', '{}'::jsonb),
  ('Rune Aasly', 'Rune', 'Aasly', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Rune Aasly', '{}'::jsonb),
  ('Magne Rognlien', 'Magne', 'Rognlien', '', '', 'Event Import', 'NEW', 300000, 50, 50, 50, NOW()::text, 'Magne Rognlien | Magne Rognlien - Har lyst å kjøpe i Estepona - 300 000 euro . Sender han til Cds!! | Budsjett: 300 000 euro | Lokasjon: CDS', '{"budget_text":"300 000 euro","location":"CDS"}'::jsonb),
  ('Tor Arne Berg', 'Tor Arne', 'Berg', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Tor Arne Berg', '{}'::jsonb),
  ('Per-Erik Aaserud', 'Per-Erik', 'Aaserud', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Per-Erik Aaserud', '{}'::jsonb),
  ('Vidar Tønnesen', 'Vidar', 'Tønnesen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Vidar Tønnesen', '{}'::jsonb),
  ('Tone Førsund', 'Tone', 'Førsund', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Tone Førsund', '{}'::jsonb),
  ('Nina Skau', 'Nina', 'Skau', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Nina Skau', '{}'::jsonb),
  ('Wenche Grude', 'Wenche', 'Grude', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Wenche Grude', '{}'::jsonb),
  ('Reidun Sæter', 'Reidun', 'Sæter', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Reidun Sæter', '{}'::jsonb),
  ('Stein Bråthen', 'Stein', 'Bråthen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Stein Bråthen', '{}'::jsonb),
  ('Bjørn Tore Brøske', 'Bjørn Tore', 'Brøske', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Bjørn Tore Brøske', '{}'::jsonb),
  ('Svein Olav Næss', 'Svein Olav', 'Næss', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Svein Olav Næss', '{}'::jsonb),
  ('Torbjørn Engeland', 'Torbjørn', 'Engeland', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Torbjørn Engeland', '{}'::jsonb),
  ('Torild Grete Løv', 'Torild Grete', 'Løv', '', '', 'Event Import', 'NEW', 300000, 50, 50, 50, NOW()::text, 'Torild Grete Løv, - Har bestilt VT med fast. Vurderer NORD / SØR inntil 300 000 euro | Budsjett: 300 000 euro', '{"budget_text":"300 000 euro"}'::jsonb),
  ('Vidar Tønnessen', 'Vidar', 'Tønnessen', '', '', 'Event Import', 'NEW', 300000, 50, 50, 50, NOW()::text, 'Vidar Tønnessen  - Må selge på hamar. Men vil ha 3 soverom CB - budsjett 300 000 eur . Sendt mail | Budsjett: 300 000 eur', '{"budget_text":"300 000 eur"}'::jsonb),
  ('Tone Lerdahl', 'Tone', 'Lerdahl', '', '', 'Event Import', 'NEW', 200000, 50, 50, 50, NOW()::text, 'Tone Lerdahl - Veldig klar! Budsjett 2 MNOK. Vurderer en VT i mars evt aug/sept | Budsjett: 2 MNOK', '{"budget_text":"2 MNOK"}'::jsonb),
  ('Tore Gjølstad', 'Tore', 'Gjølstad', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Tore Gjølstad | Tore Gjølstad - veldig gode leads. Avtalt møte . Budsjetrt 550 k - Nord / sør', '{}'::jsonb),
  ('Sissel Kjus', 'Sissel', 'Kjus', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Sissel Kjus', '{}'::jsonb),
  ('Inge Fjalsett', 'Inge', 'Fjalsett', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Inge Fjalsett', '{}'::jsonb),
  ('Trond Nyland', 'Trond', 'Nyland', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Trond Nyland', '{}'::jsonb),
  ('Frode Arntsen', 'Frode', 'Arntsen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Frode Arntsen', '{}'::jsonb),
  ('Anne Mette Ramm', 'Anne Mette', 'Ramm', '', '', 'Event Import', 'NEW', 300000, 50, 50, 50, NOW()::text, 'Anne Mette Ramm | Anne Mette Ramm - Budsjeett 3 MNOK - Ønsker cb NORD | Budsjett: 3 MNOK | Lokasjon: CB Nord', '{"budget_text":"3 MNOK","location":"CB Nord"}'::jsonb),
  ('Rino Lillefosse', 'Rino', 'Lillefosse', '', '', 'Event Import', 'NEW', 250000, 50, 50, 50, NOW()::text, 'Rino Lillefosse | Rino Lillefosse - Ønsker CB NORD - budsjett 2-2,5 mnok  Har familie der. | Budsjett: 2-2,5 mnok Har familie der | Lokasjon: CB Nord', '{"budget_text":"2-2,5 mnok Har familie der","location":"CB Nord"}'::jsonb),
  ('Hilde Myhre', 'Hilde', 'Myhre', '', '', 'Event Import', 'NEW', 500000, 50, 50, 50, NOW()::text, 'Hilde Myhre | Hilde Myhre og Tor Arne  - vil kjøpe nybygg inntil 5 MNOK i sør | Hilde Myhre , budsjett inntil 3 MNOK. Kjøpe innen 2 år. Vurderer CB Nord . Sender til amo | Budsjett: 5 MNOK | Lokasjon: CB Nord', '{"budget_text":"5 MNOK","location":"CB Nord"}'::jsonb),
  ('Frode Opland', 'Frode', 'Opland', '', '', 'Event Import', 'NEW', 250000, 50, 50, 50, NOW()::text, 'Frode Opland | Frode Opland - Vil sjekke muligheter i Spania - er syk og trenger varme . budsjett 2-2,5 MNOK | Budsjett: 2-2,5 MNOK', '{"budget_text":"2-2,5 MNOK"}'::jsonb),
  ('Anne Marie Lindmark', 'Anne Marie', 'Lindmark', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Anne Marie Lindmark', '{}'::jsonb),
  ('Tor Arne', 'Tor', 'Arne', '', '', 'Event Import', 'NEW', 500000, 50, 50, 50, NOW()::text, 'Hilde Myhre og Tor Arne  - vil kjøpe nybygg inntil 5 MNOK i sør | Budsjett: 5 MNOK', '{"budget_text":"5 MNOK"}'::jsonb),
  ('Pål Sønsteby', 'Pål', 'Sønsteby', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Pål Sønsteby', '{}'::jsonb),
  ('Espen Langslet', 'Espen', 'Langslet', '', '', 'Event Import', 'NEW', 200000, 50, 50, 50, NOW()::text, 'Espen Langslet | Espen Langslet og Lise Wibe - 2 mill NOK, CB Sør - ikke lenger en 45 min unna flyplassen . De er ikke klare, ser ca 2-3 år frem i tid | Budsjett: 2 mill | Lokasjon: CB Sør', '{"budget_text":"2 mill","location":"CB Sør"}'::jsonb),
  ('Morten Kristiansen', 'Morten', 'Kristiansen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Morten Kristiansen', '{}'::jsonb),
  ('Tormod Stene', 'Tormod', 'Stene', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Tormod Stene', '{}'::jsonb),
  ('Håkon Holth', 'Håkon', 'Holth', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Håkon Holth', '{}'::jsonb),
  ('Pål og Ellen Sønsteby', 'Pål og Ellen', 'Sønsteby', '', '', 'Event Import', 'NEW', 300000, 50, 50, 50, NOW()::text, 'Pål og Ellen Sønsteby - Sør, Punta Prima. Budsjett 200 - 300K - ønsker VT til høsten | Budsjett: 200 - 300K - ønsker VT til høsten | Lokasjon: Punta Prima', '{"budget_text":"200 - 300K - ønsker VT til høsten","location":"Punta Prima"}'::jsonb),
  ('Frank og Hege Løvåsen', 'Frank og Hege', 'Løvåsen', '', '', 'Event Import', 'NEW', 400000, 50, 50, 50, NOW()::text, 'Frank og Hege Løvåsen - Vil flytte ned om 3 år. Budsjett 400 K nord for Torrevieja | Budsjett: 400 K nord for Torrevieja | Lokasjon: Torrevieja', '{"budget_text":"400 K nord for Torrevieja","location":"Torrevieja"}'::jsonb),
  ('Lise Wibe', 'Lise', 'Wibe', '', '', 'Event Import', 'NEW', 200000, 50, 50, 50, NOW()::text, 'Espen Langslet og Lise Wibe - 2 mill NOK, CB Sør - ikke lenger en 45 min unna flyplassen . De er ikke klare, ser ca 2-3 år frem i tid | Budsjett: 2 mill | Lokasjon: CB Sør', '{"budget_text":"2 mill","location":"CB Sør"}'::jsonb),
  ('Morten og Tove Kristiansen', 'Morten og Tove', 'Kristiansen', '', '', 'Event Import', 'NEW', 500000, 50, 50, 50, NOW()::text, 'Morten og Tove Kristiansen  - Nord - 3-5MNOK. Vi avtalt møte 4. mars | Budsjett: 5MNOK', '{"budget_text":"5MNOK"}'::jsonb),
  ('Tormod og May Brit', 'Tormod og May', 'Brit', '', '', 'Event Import', 'NEW', 400000, 50, 50, 50, NOW()::text, 'Tormod og May Brit - Budsjett ca 400k - avtalte teams møte | Budsjett: ca 400k - avtalte teams møte', '{"budget_text":"ca 400k - avtalte teams møte"}'::jsonb),
  ('Harald Aastorp', 'Harald', 'Aastorp', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Harald Aastorp', '{}'::jsonb),
  ('Thomas Løvold', 'Thomas', 'Løvold', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Thomas Løvold', '{}'::jsonb),
  ('Bente Vang', 'Bente', 'Vang', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Bente Vang', '{}'::jsonb),
  ('Nina Holtet', 'Nina', 'Holtet', '', '', 'Event Import', 'NEW', 450000, 50, 50, 50, NOW()::text, 'Nina Holtet | Nina Holtet, ønsker visningstur - Har budsjett på 450 K Eur. CDS. | Budsjett: på 450 K Eur | Lokasjon: CDS', '{"budget_text":"på 450 K Eur","location":"CDS"}'::jsonb),
  ('Jan Sørhus', 'Jan', 'Sørhus', '', '', 'Event Import', 'NEW', 100000, 50, 50, 50, NOW()::text, 'Jan Sørhus | Jan Sørhus - Vil ha leilighet max 1 mill NOK. Tror dette blir vanskelig og jeg snakket med han om at lån i spania kun går opp til 70 % . | Budsjett: 1 mill', '{"budget_text":"1 mill"}'::jsonb),
  ('Kari Follo Fjellvang', 'Kari Follo', 'Fjellvang', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Kari Follo Fjellvang - Ønsker Costa Blanca. Skal til CB en mnd i juni / juli  avtalte møte', '{}'::jsonb),
  ('Stig Jaran Olsen', 'Stig Jaran', 'Olsen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Stig Jaran Olsen - Ønsker visningstur til CB sør om 2 uker!! Spania1 må ordne visning. Sendt leads til Janne. | Lokasjon: CB Sør', '{"location":"CB Sør"}'::jsonb),
  ('Harald Åstorp', 'Harald', 'Åstorp', '', '', 'Event Import', 'NEW', 400000, 50, 50, 50, NOW()::text, 'Harald Åstorp og kona, ser på Spania for sin helse, og datter er revmatiker som ønsker å bruke boligen for trening / sykling. Ca budsjett 400 K EUR | Budsjett: 400 K EUR', '{"budget_text":"400 K EUR"}'::jsonb),
  ('Espen Nordheim', 'Espen', 'Nordheim', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Espen Nordheim', '{}'::jsonb),
  ('Vebjørn Tveiterås', 'Vebjørn', 'Tveiterås', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Vebjørn Tveiterås', '{}'::jsonb),
  ('Torgeir Fjell', 'Torgeir', 'Fjell', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Torgeir Fjell', '{}'::jsonb),
  ('Anette Mørk', 'Anette', 'Mørk', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Anette Mørk', '{}'::jsonb),
  ('Kjell Fevik', 'Kjell', 'Fevik', '', '', 'Event Import', 'NEW', 400000, 50, 50, 50, NOW()::text, 'Kjell Fevik - Var på event 17.nov  - skal avtale VT til CB eller CDS | Kjell Fevik (Eidsvoll) - plass for vinter, leie ut når ikke i bruk. Alicante eller Solkysten. 300-400 000 eur | Budsjett: 400 000 eur | Lokasjon: CDS', '{"budget_text":"400 000 eur","location":"CDS"}'::jsonb),
  ('Lars Gjøseth', 'Lars', 'Gjøseth', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Lars Gjøseth - Budsjetrt 600K , ønsker nybygg, ser på La fince / Las Colinas golf , Altea . Han sjekker nå mulighet i CDS | Lokasjon: CDS', '{"location":"CDS"}'::jsonb),
  ('Tor-Erik Leksås', 'Tor-Erik', 'Leksås', '', '', 'Event Import', 'NEW', 300000, 50, 50, 50, NOW()::text, 'Tor-Erik Leksås - Investere/utleie , Budsjett ca 2,5- 3 MNOK - Skal ned og kikke i feb/mars | Budsjett: ca 2,5- 3 MNOK - Skal ned og kikke i feb/mars', '{"budget_text":"ca 2,5- 3 MNOK - Skal ned og kikke i feb/mars"}'::jsonb),
  ('Per Øyvind Stensrud', 'Per Øyvind', 'Stensrud', '', '', 'Event Import', 'NEW', 350000, 50, 50, 50, NOW()::text, 'Per Øyvind Stensrud - Budsjet 3-3,5 MNOK. Sjekker lån i norge + spania | Budsjett: 3,5 MNOK', '{"budget_text":"3,5 MNOK"}'::jsonb),
  ('Agnieszka Strzelec', 'Agnieszka', 'Strzelec', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Agnieszka Strzelec og Stian Johansen -  Gode leads !! Budsjett  7 milnok ++ | Budsjett: 7 milnok ++', '{"budget_text":"7 milnok ++"}'::jsonb),
  ('Stian Johansen', 'Stian', 'Johansen', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Agnieszka Strzelec og Stian Johansen -  Gode leads !! Budsjett  7 milnok ++ | Budsjett: 7 milnok ++', '{"budget_text":"7 milnok ++"}'::jsonb),
  ('Jovance Popovic', 'Jovance', 'Popovic', '', '', 'Event Import', 'NEW', 350000, 50, 50, 50, NOW()::text, 'Jovance Popovic, nybolig 350 000 euro | Budsjett: 350 000 euro', '{"budget_text":"350 000 euro"}'::jsonb),
  ('Janne Krokaas', 'Janne', 'Krokaas', '', '', 'Event Import', 'NEW', 400000, 50, 50, 50, NOW()::text, 'Janne Krokaas, 400 000 euro, nybolig | Budsjett: 400 000 euro', '{"budget_text":"400 000 euro"}'::jsonb),
  ('Unnar Aarsæther', 'Unnar', 'Aarsæther', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Unnar Aarsæther, 260 000', '{}'::jsonb),
  ('Helge Sørbye', 'Helge', 'Sørbye', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Helge Sørbye og kona ønsker nybolig - har mulighet nå i mai til å reise! Sender de til Janne!! Veldig bra par med midler!', '{}'::jsonb),
  ('Else-Beate Pytte', 'Else-Beate', 'Pytte', '', '', 'Event Import', 'NEW', 350000, 50, 50, 50, NOW()::text, 'Else-Beate Pytte og mann, Gode leads . 3,5 Mnok . Sjekker finansiering .  Sendt leads til Cb og CDS | Budsjett: 3,5 Mnok | Lokasjon: CDS', '{"budget_text":"3,5 Mnok","location":"CDS"}'::jsonb),
  ('Sven Petter Nordbye', 'Sven Petter', 'Nordbye', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Sven Petter Nordbye, ønsker VT . Nord eller Sør . Har sendt i Amo', '{}'::jsonb),
  ('Ståle Skogland', 'Ståle', 'Skogland', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Ståle Skogland,  Vurderer nord', '{}'::jsonb),
  ('Arve Abelsen', 'Arve', 'Abelsen', '', '', 'Event Import', 'NEW', 400000, 50, 50, 50, NOW()::text, 'Arve Abelsen, budsjett 300-400k | Budsjett: 300-400k', '{"budget_text":"300-400k"}'::jsonb),
  ('Magne Haugum', 'Magne', 'Haugum', '', '', 'Event Import', 'NEW', 0, 50, 50, 50, NOW()::text, 'Magne Haugum - Gode Leads (kjøper i mai/juni)', '{}'::jsonb),
  ('Anne Kari Killi', 'Anne Kari', 'Killi', '', '', 'Event Import', 'NEW', 300000, 50, 50, 50, NOW()::text, 'Anne Kari Killi  (CB sør - Torrevija ca. 3 MNOK) - har hund | Budsjett: 3 MNOK | Lokasjon: CB Sør', '{"budget_text":"3 MNOK","location":"CB Sør"}'::jsonb),
  ('Harald Jaksland', 'Harald', 'Jaksland', '', '', 'Event Import', 'NEW', 450000, 50, 50, 50, NOW()::text, 'Harald Jaksland og kona - Costa del Sol, 3 roms leilighet, 350-450 000 euro. Helst ikke lenger vest enn Marbella. | Budsjett: 450 000 euro | Lokasjon: Costa del Sol', '{"budget_text":"450 000 euro","location":"Costa del Sol"}'::jsonb)
ON CONFLICT DO NOTHING;

-- 151 leads totalt