
CREATE TABLE public.brands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID DEFAULT auth.uid() NOT NULL,
  name TEXT NOT NULL,
  type TEXT,
  email TEXT,
  logo_url TEXT,
  CONSTRAINT brands_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
);

ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated user to access their own brands"
ON public.brands
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
